Implement relation charm libraries
canonical/data-platform-libs pull request #1
Opened 2022-05-25 17:47 UTC by marceloneppel

2022-05-26 20:43 UTC, paulomach reviewed
LGTM, but I'm biased on this, so i'll keep the approvals for others

2022-05-26 20:43 UTC, paulomach commented on requirements.txt
> +ops >= 1.2.0
should we bump it to 1.4?

2022-05-27 10:26 UTC, jnsgruk approved these changes
This is a nice start, thanks Marcelo

2022-05-27 10:26 UTC, jnsgruk commented on lib/charms/data_platform_libs/v0/database_requires.py
> +        self.database = DatabaseRequires(self, "database")
Just to be super explicit for documentation's sake, I'd specify this as a keyword arg:

```suggestion
        self.database = DatabaseRequires(self, relation_name="database")
```

2022-05-27 11:14 UTC, PietroPasotti commented
Many of the files added by charmcraft init are not needed, and I think they should be removed.
Take a look at https://github.com/canonical/charm-lib-template
I believe the only files that are 'required' to create and publish a lib are metadata.yaml (only the 'name' field is necessary in there) and /lib/charms/.../lib_file.py

So if you want to de-clutter the PR, /src should go. as well as .jujuignore and charmcraft.yaml

2022-05-27 11:25 UTC, PietroPasotti requested changes
Some minor comments, some of which need double checking :)

2022-05-27 11:25 UTC, PietroPasotti commented on lib/charms/data_platform_libs/v0/database_requires.py
> +    pass
pass is not necessary since there's a docstring

2022-05-27 11:25 UTC, PietroPasotti commented on lib/charms/data_platform_libs/v0/database_requires.py
> +        old_data = json.loads(self.relation.data[self.charm.model.app].get("data", "{}"))
As mentioned in a call earlier today: are we sure that the application databag can be safely used to cache data? I.e. if the app is scaled to 0 and back up to N, will the application data be wiped or persisted?
If the remote application does?

2022-05-27 11:25 UTC, PietroPasotti commented on lib/charms/data_platform_libs/v0/database_requires.py
> +    def username(self) -> str:
the return type of this prop (and many others) should be Optional[str]

2022-05-27 11:25 UTC, PietroPasotti commented on lib/charms/data_platform_libs/v0/database_requires.py
> +        return {
that's just me, but I'd create a `Diff` namedtuple to type this return object and make its consumption easier (and more maintainable) etc... But consider this a nit :D

2022-05-27 11:25 UTC, PietroPasotti commented on lib/charms/data_platform_libs/v0/database_requires.py
> +    pass
(that applies to the other events too)

2022-05-27 14:18 UTC, PietroPasotti commented
Looking a lot better now! Green light from my side :)

2022-05-31 08:18 UTC, WRFitch approved these changes

2022-05-31 12:05 UTC, marceloneppel commented on requirements.txt
> +ops >= 1.2.0
Updated on https://github.com/canonical/data-platform-libs/pull/1/commits/8e7f1083d4b3621e85f6aa77152285833f423e39.

2022-05-31 12:05 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/database_requires.py
> +        self.database = DatabaseRequires(self, "database")
Nice! Updated on https://github.com/canonical/data-platform-libs/pull/1/commits/ba58e91a5c7b2822d84e60089c318f25774c6ec7.

2022-05-31 12:08 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/database_requires.py
> +    def username(self) -> str:
Fixed on https://github.com/canonical/data-platform-libs/pull/1/commits/3ab2626f83db01fc89a25c9c6e13558d3e9d62e1.

2022-05-31 12:10 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/database_requires.py
> +        old_data = json.loads(self.relation.data[self.charm.model.app].get("data", "{}"))
John Meinel confirmed to me yesterday that it should work: "Scaling to 0 units is not removing the application. Thus I would expect the unit data to go away, but the application data in the relation to still be there."

2022-05-31 12:11 UTC, marceloneppel commented on tox.ini
> +    # codespell {[vars]lib_path}
Nice. Thanks for catching it. Fixed on https://github.com/canonical/data-platform-libs/pull/1/commits/39c1e7388ea6ba4df0b0fce519b6863a373763d1.

2022-05-31 12:13 UTC, merged