[DPE-3294] Add mongos requires
canonical/data-platform-libs pull request #133
Opened 2024-01-22 08:34 UTC by MiaAltieri

## Issue:
DPE-3294 Requires that data-integrator charm can be integrated with the `mongos` charm. In order to be integrated with the `mongos` charm it needs access to `MongosRequirer`

## Solution
migrate `MongosRequirer` from `mongos` charm libs to `data-platform-libs`

2024-01-22 09:05 UTC, MiaAltieri commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class MongosRequirer(Object):
this class was already reviewed in the `mongos` charm, only migrating the code to here.

2024-01-22 10:10 UTC, dmitry-ratushnyy approved these changes

2024-01-22 10:24 UTC, Mehdi-Bendriss approved these changes

2024-01-22 11:02 UTC, welpaolo reviewed
Please add also `MongoProvides` relation as part of the PR. 
Do you also plan to add some tests on the new interface ?

2024-01-24 17:50 UTC, juditnovak requested changes
Pls Guys, may I be a reviewer on these PRs?
(If I could receive an MM notification I'd be most grateful!!!! Thx very much)

Thx very much!

2024-02-22 08:00 UTC, closed without merging