[DPE-3874] `dict` representation for Data (i.e. "back to databag" :-) )
canonical/data-platform-libs pull request #147
Opened 2024-03-21 17:51 UTC by juditnovak

This PR is the "continuation" of [earlier POC](https://github.com/canonical/data-platform-libs/pull/143).

2024-03-25 21:03 UTC, welpaolo reviewed
The implementation looks good. I feel there is the need for some integration tests tests to check the handling of relation data as dictionary. 

Do you think it will be possible (just for testing purposes) to have "normal" and dict representation to work in the same testing charm?

2024-03-26 10:25 UTC, juditnovak commented
@welpaolo your question/request about integration tests is indeed something worth discussing. 
I apologize, my response is long, as to me it's a _conceptual_ matter (not in terms of code but in terms of tests). 
I'm glad to sync on this after your holidays if preferred -- as we usually do :-) 

In fact, I was thinking to add a comment on this topic to the **Description**, when I created the PR, but I didn't do it at the end.

There are  purposefully no integration tests here. I don't think we should have them this time.
However, there may be something else to be tested instead -- that is missing currently. I rather propose that extension (see later).

The `dict` interface should be VERY strictly no more than a "syntactic sugar", a lightweight wrapper around the 3(+1) interface functions we are providing:
 - `fetch_relation_data()` (and `fetch_relation_field()`
 - `update_relation_data()`
 - `delete_relation_data()`

These 3 are implementing the _real_ functionality and must be particularly carefully tested with integration tests. (I think we're pretty good on that right now.)

The `dict` wrapper MUSTN'T invent anything. It should add NO new functionality. It must _strictly_ do no more than apply the underlying interface function that corresponds to the `dict` call, with the parameters that were shipped.

To test this lightweight wrapper layer (new interface), I see no value in integration tests. ALL that the wrapper has to provide is rather a unit test material.

However I do see a missing element in the current unit tests indeed. They do verify every aspect of the `dict` behavior, however they _don't_ ensure that it is no more than a thin wrapper around the interface functions.
(While it is VERY important to ensure that further additions to the code would preserver the wrapper nature, i.e. "no functionality would be invented" within a `DataDict` object.)

Thus, what I rather propose is that I would extend the current unittests with one more, that is verifying that the `dict` wrapper is calling the underlying interface functions. (IT is one of the few cases where I find mocks being the right thing to use.)
Also I would add an explanation (both on the code (`class`) an in the tests) how this concept MUST be preserved.

[NOTE: While I'm VERY keen on through testing, I also think it's important to write tests thoughtfully, in a sense to make sure that we are testing the right thing in the right place, at the right time. Especially when dealing with complex code, tests can get confusing, difficult to extend, difficult to "debug", loose descriptive nature if not developed carefully.]

One more reason why I find it more beneficial not to add another test charm, is because we _will_ have a new test charm in [my upcoming, heavyweight change](https://github.com/canonical/data-platform-libs/pull/137) -- which _will_ require a new test charm :-) 
(Sadly it won't be convenient to provide a full test coverage for the `dict` usage there, but if preferred I can use the `dict` syntax in that one :-) So that `data-platform-libs` provide  a charm using the syntax.). 
But I think it may keep the testsuite more clean if we don't add too many test charms... as it may get confusing, difficult to follow...

(BTW regarding "real-life" functionality: of course this code is being used in the PR mentioned in the **Description**, functioning real well :-) Just to reassure that the proposal has been executed by actual charms, showing good results :-) )

Huh, I apologize for writing a novel here... Testing is a very important topic for me :sweat_smile:

2024-03-26 16:06 UTC, juditnovak commented
Hmmmmm.... And another missing thing here :sweat_smile: 

Those unittests we should have on the Cross-charm relation interfaces as well :facepalm: 

I'm adding this missing bit as well!!!!!

2024-03-27 12:34 UTC, deusebio requested changes
Given this is an implementation to keep as close as possible to `dict`, I've been a bit more picky (and we should probably be) for the typing and naming used in the signatures.

2024-03-27 12:34 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def as_dict(self, relation_id: int):
**todo** I blieve it is safe to type it as

```
def as_dict(self, ...) -> dict:
```

2024-03-27 12:34 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class DataDict(dict):
Uhm, this only extends `Dict[str, str]` or any dict?

2024-03-27 12:34 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        return list(self.all_data().keys())
To just keep closer to original implementation, we can probably avoid the list conversion, and just type with common keys() output

2024-03-27 12:34 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def all_data(self) -> Dict[str, str]:
```suggestion
    @property
    def data(self) -> Dict[str, str]:
```
```suggestion
    def all_data(self) -> Dict[str, str]:
```

**niptick**

2024-03-27 12:34 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def values(self) -> List[str]:
as above

2024-03-27 12:34 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def items(self) -> List[Tuple[str, str]]:
as above

2024-03-27 12:34 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def has_key(self, k) -> bool:
```suggestion
    def has_key(self, key: str) -> bool:
```

2024-03-27 12:34 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        return set(self.keys()) == set(d.keys()) and all(self[key] == d[key] for key in d)
**question** why not using built-in equality for dicts `self.data == d`? Note sure I was able to understand why elsewhere you used built-in implementations (e.g. `__repr__`) and not here

2024-03-27 20:18 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class DataDict(dict):
I meant to implement the `dict[str,str]`, given we know that keys and values can only be strings, i.e.

```
class DataDict(dict[str, str]):
```

By the way, it is also probably better to extend the `UserDict` class rather than `dict` (see [here](https://stackoverflow.com/questions/7148419/subclass-dict-userdict-dict-or-abc)), so 

```
class DataDict(UserDict[str, str]):
```

2024-03-28 10:49 UTC, marcoppenheimer commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def __getitem__(self, key: str) -> Optional[str]:
**todo:** I don't think this can be 'Optional'. We should raise a KeyError if we can't find the key, like a normal dict.

2024-03-29 17:06 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class DataDict(dict):
All right, I see your point. Sorry, it's a very valid consideration. My bad, I wasn't aware of generics here. Thanks for pointing it out, it was very good info.

I'm thinking of this, and... I'm not sure what may be the best here.

On one hand, I'm thinking if we may want to keep the implementation flexible (`Dict[str, Any]`?), typically in case in the future, for any unforeseen reason we may want to have more complex structures (`list`, `dict`, etc.) as values. It may come handy not to restrict more than necessary.

(Of course, on the other hand it's true that current `get()`, `__getitem__()`, etc. are returning `str` only... We may want to keep that on `Any` as well...?)

Thinking.... Pro-s/con-s are welcome.

2024-03-29 17:27 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        return set(self.keys()) == set(d.keys()) and all(self[key] == d[key] for key in d)
It actually does, my mistake. Changed accordingly.

2024-03-29 17:28 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def __getitem__(self, key: str) -> Optional[str]:
Done.

2024-03-29 17:29 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def has_key(self, k) -> bool:
Done.

2024-03-29 17:29 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def items(self) -> List[Tuple[str, str]]:
Done.

2024-03-29 17:29 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def values(self) -> List[str]:
Done.

2024-03-29 17:29 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def all_data(self) -> Dict[str, str]:
Done.

2024-03-29 17:30 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        return list(self.all_data().keys())
Done.

2024-03-29 17:32 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def as_dict(self, relation_id: int):
Changed to `UserDict`, kept in-line with the discussion below.

2024-03-29 17:32 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def has_key(self, k) -> bool:
Done.

2024-04-02 07:56 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class DataDict(dict):
I believe it should be `[str, str]`, as that is the only type allowed for data bags. This data structure is pretty low-level and close to the databag, so I would keep the signature aligned. If someone wants to create more "structure", like simple types (int, float, list, ...) but even more complex with user-derived dataclasses, they should probably implement serialization/deserialization starting from the functionalities exposed by this class (that are with strings)

2024-04-02 12:03 UTC, deusebio approved these changes
LGMT! Thanks!

2024-04-02 20:26 UTC, welpaolo approved these changes
LGTM

2024-04-02 23:51 UTC, merged