[DPE-3906][BUGFIX] dict implementation not supporting Python 3.9> (issue #152)
canonical/data-platform-libs pull request #153
Opened 2024-04-04 17:46 UTC by juditnovak

# URGENT FIX -- Python 3.9> compatiblity broken

Once again I had to remember the hard way: `data_interfaces` MUST be strongly backwards compatible.

Both in terms of code and in terms of Python versions, etc.

Adding generics to the `dict` implementation parent class broke Python 3.9> compatibility.

The proposed fix executes correctly on earlier Python versions as well: https://github.com/canonical/data-platform-libs/actions/runs/8559046518

2024-04-04 18:25 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> -class DataDict(UserDict[str, str]):
Note: I know there are ways to have the generics selective to version.

However I'm wondering to rather not enforce typing here, leaving it open for potential future extensions.

2024-04-04 19:49 UTC, marceloneppel requested changes

2024-04-04 19:49 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> -class DataDict(UserDict[str, str]):
Indico build still fails due to generics at `def as_dict(self, relation_id: int) -> UserDict[str, str]:` (line 1039).

2024-04-04 20:45 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> -class DataDict(UserDict[str, str]):
GREAT CATCH THANK U SO MUCH!!!!!!!!!!!

2024-04-04 21:22 UTC, deusebio approved these changes
That's a pity we are stuck to be compatible to old version of python. Why are people still using 3.8?!? EOL is coming up this year. 

**niptick** I feel the title and the commit reads better to say "Python <3.9"

2024-04-04 21:45 UTC, marcoppenheimer commented
I have responded specifically, but I don't think we should support non-latest-LTS Ubuntu Python versions.

2024-04-04 22:07 UTC, juditnovak commented
@marceloneppel , @deusebio  I don't think we should limit our lib users in their choice of Ubuntu/Python version. We have many charms (like wordpress or indico). Neither we should deprive latest enhancements (or bugfixes) from them. 

We can have pretty, up-to-date code in our charms where we're in control of Ubuntu/Python versions, where we know what our clients need/use, etc. But generic interfaces that we provide should be more allowing than that.

As explained in the [related issue](https://github.com/canonical/data-platform-libs/issues/152), the problem was raised on the public Matrix channel by the Indico charm team: https://matrix.to/#/!BukWfnyOTgQSKAxdtT:ubuntu.com/$X0SV2M_Xb-MYL3gOAmXJzuFVSOeFQc9MKXBIwDUwA6w?via=ubuntu.com&via=matrix.org

2024-04-04 22:35 UTC, deusebio commented
To me, EoL is a good enough reason to stop making sure code is backward compatible with that version. Otherwise how do we draw the line between which versions you want to be compatible with?

Anyhow, I would probably add a matrix on the CI (only unittests in my opinion) against the different python versions we support. Of course, outside of this PR if the other team is blocked and we need to merge this asap.

2024-04-05 07:23 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> -class DataDict(UserDict[str, str]):
Done

2024-04-05 07:44 UTC, juditnovak commented
Let's be honest -- we introduced a breaking change ;-) 
While indeed we may want to consider what level of backwards compatibility should our libs support -- equally we should avoid incompatible/breaking changes :-)  At least across minor versions

2024-04-05 10:02 UTC, juditnovak commented
Adding a summary of team discussion on this matter, with @delgod involved.

Some of our products (like PGbouncer) are supporting 20.04. We must respect backwards compatibility with applications using our products.

2024-04-05 12:32 UTC, marceloneppel approved these changes
LGTM! Just remember to bump `LIBPATCH`, as it's already 32 on the [main](https://github.com/canonical/data-platform-libs/blob/3b06c74e3496e7487acb8974c18ae51196328fb5/lib/charms/data_platform_libs/v0/data_interfaces.py#L334) branch.

2024-04-05 12:34 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> -class DataDict(UserDict[str, str]):
Thanks! :) I tested the changes on Indico, and its build worked now.

2024-04-05 14:05 UTC, marceloneppel approved these changes

2024-04-05 15:05 UTC, merged