[MISC] Fix Kafka and OpenSearch spelling
canonical/data-platform-libs pull request #161
Opened 2024-04-18 16:55 UTC by deusebio

2024-04-18 17:06 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class KafkaProviderEvent(RelationEvent):
I have reverted this change, as this would not have been consistent with the Database classes. But I'm wondering why we kept `Provides` here, and not change it to "Provider"? It seems we did not do this for:

* `*ProvidesEvent`
* `*ProvidesEvents`

Are these used at all in any charm and we need to keep backward compatibility on these?

2024-04-19 13:53 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class OpenSearchProviderEventHandlers(EventHandlers):
Was there an agreement on Opensearch side?

This means they (us) need to update the code.

Otherwise they (us) can't update libs.

2024-04-19 14:59 UTC, juditnovak requested changes
This is a breaking change for Opensearch. We need to sync with the team.

2024-04-19 15:15 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class OpenSearchProviderEventHandlers(EventHandlers):
Are you already using the new pattern on opensearch? If not, it should be transparent, since this is a new class appearing some PRs ago. I believe this misspelling slipped in the review process (I would regard this as a tiny bug), but up to them (you) what to do. I can roll back. Just be aware you are a tiny bit off the standard there.

2024-04-22 06:31 UTC, welpaolo approved these changes
Looks good to me

2024-04-22 13:38 UTC, deusebio commented
I have reverted the OS modification. If you'll want to implement that, you can easily one the commit in this PR

2024-04-22 20:47 UTC, juditnovak approved these changes

2024-04-22 20:51 UTC, merged

2024-04-24 11:57 UTC, marceloneppel commented
The LIBPATCH wasn't bumped.

2024-04-24 13:07 UTC, deusebio commented
Yes, we are aware! https://github.com/canonical/data-platform-libs/pull/165