[BUGFIX] URI exists while re-creating secret with modified label
canonical/data-platform-libs pull request #170
Opened 2024-05-24 13:55 UTC by juditnovak

2024-05-27 05:54 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> -        old_meta.remove_all_revisions()
We need this in a long term, but I rather leave "garbage" around for now, and bring this code back after having verified that under no circumstances we may remove this data pre-mature.

See issue on this matter https://github.com/canonical/data-platform-libs/issues/171

2024-05-27 05:56 UTC, juditnovak commented on tox.ini
> +
Instead of the current hard copy of the previous lib versions, we'll be fetching these files from the git repo dynamically.
The current solution is temporary.

2024-05-27 06:17 UTC, juditnovak commented on tests/unit/test_data_interfaces.py
> -            secret = self.harness.model.get_secret(label=f"database.{scope}")
Disabled for now, to be re-enabled in https://github.com/canonical/data-platform-libs/issues/171

2024-05-27 07:50 UTC, taurus-forever approved these changes
I am giving LGTM to library changes here, as I have tested them on weekend and the original issue is no longer reproducible. Well done.

Re: tests... I simply cannot load 4*3.5K tests into my mind... 
and this makes me crazy:
```
    cp tests/integration/data/data_interfaces.py.4 tests/integration/data/data_interfaces.py_old
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}/integration/test_rolling_upgrade_from_specific_version.py
```

Why do you commit files py.1-4 and copying them into py_old is unclear for me.... please add to PR description the black magic logic. Tnx!

Anyway LGTM for the library fix to unblock PG promotion to candidate for Landscape Team.

2024-05-27 07:58 UTC, delgod requested changes
The ticket number should be part of the PR description.
The PR description should clearly explain the problem and how the new code solves it.
At least one technical reviewer should be added.

2024-05-27 16:38 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        self._secret_uri = None
Underlying logic: Normally this helper field is to hold the URI of a secret (in case the secret was newly created, or fetched by URI).

At this point, we are switching the `self` (CachedSecret) object to point to a new secret object (that's associated with the new label).

Thus we have to "unlink" the object from the old URI. (Otherwise new secret creation is blocked: as the error in https://warthogs.atlassian.net/browse/DPE-4416 was indicating so.)

2024-05-27 16:52 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        self.current_label = None
This field is used to indicate when an upgrade was performed, where a secret label change may have happened. 

We detect dynamically if a secret with an old label may be "hanging around", from an old version of the charm. In order to ensure smooth upgrades, we are leaving the secret associated with the old label, as long as only read operations are performed on the secret.
We hold the value of the outdated label in the `CachedSecret.current_label` field (while `CachedSecret.label` is always pointing to the label that is to be used in a long term.

When the above code is executed, we are at the point of the first write operation impacting this secret.
I.e. move to the new label (by having created a brand-new secret, that's recognized by the new label).
We need to clean the `current_label` field, as we have no link to the old (labelled) secret anymore.

2024-05-27 17:44 UTC, delgod approved these changes

2024-05-27 17:55 UTC, juditnovak commented
@taurus-forever to answer your question.

We have a new test module, that performs a simulated rolling upgrade on test charms.

The initial PR (to deliver a quick yet reliable solution) took a local copy of older versions of the lib, and "rotated" them to a static location for the the test module to pick up. 

As I got the opportunity to clean up the "brute-force" approach, now the tests are dynamically fetching corresponding `latest - N` versions from git on each run of the corresponding, new pipelines.

2024-05-27 19:17 UTC, marceloneppel commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_name = f"{APPLICATION_APP_NAME}/{leader_id}"
Shouldn't you use either `DATABASE_APP_NAME` or `APPLICATION_APP_NAME` in both statements? The same happens on the code block after `# Password`.

2024-05-27 19:17 UTC, marceloneppel commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_app_name = f"{APPLICATION_APP_NAME}/{leader_app_id}"
Shouldn't you use `APPLICATION_APP_NAME` in both statements?

2024-05-27 19:17 UTC, marceloneppel commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_app_name = f"{APPLICATION_APP_NAME}/{leader_app_id}"
Shouldn't you use `APPLICATION_APP_NAME` in both statements?

2024-05-27 19:17 UTC, marceloneppel commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_app_name = f"{APPLICATION_APP_NAME}/{leader_app_id}"
Shouldn't you use `APPLICATION_APP_NAME` in both statements?

2024-05-27 19:17 UTC, marceloneppel commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_name = f"{APPLICATION_APP_NAME}/{leader_id}"
As these tests are running on K8s and you have only one unit of each app, you can always consider `0` the leader ID.

2024-05-27 19:22 UTC, juditnovak commented on tests/unit/test_upgrade.py
> +            "dependencies": {"gandalf_the_grey": "~1.0", "bilbo": value},
Codespell inisisted that `durin` should be `during`

2024-05-27 19:23 UTC, juditnovak commented on tox.ini
> +    bash
Good point, cleaing it up. (Traces of earlier attempts).

2024-05-27 19:28 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    await upgrade_to_new_version(ops_test, DATABASE_APP_NAME)
Indeed this is not needed (though harmless). Removing it.

2024-05-27 19:30 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    # Both secret and databag content can be modified -- even twice ;-)
Running it in a loop is a different thing as it results in multiple event handlers.

We need to test in the same event handler (typically for this bug, but also useful in general).

2024-05-27 19:32 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_name = f"{DATABASE_APP_NAME}/{leader_id}"
:facepalm: 

Thanks, good call :sweat_smile:

2024-05-27 19:41 UTC, juditnovak commented on tox.ini
> +    bash
Done

2024-05-27 19:41 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    await upgrade_to_new_version(ops_test, DATABASE_APP_NAME)
Done

2024-05-27 19:41 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_name = f"{DATABASE_APP_NAME}/{leader_id}"
Done

2024-05-27 19:49 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_name = f"{APPLICATION_APP_NAME}/{leader_id}"
Done.

Yes, I see your point for k8s. (Thank for the info, I didn't know. Opensearch is VM only :-) ). 

For now I left it consistent, with the "usual" terminology. (What if we start testing the libs for VM too one day.../ :-) )

2024-05-27 19:49 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_app_name = f"{APPLICATION_APP_NAME}/{leader_app_id}"
Done.

2024-05-27 19:49 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_app_name = f"{APPLICATION_APP_NAME}/{leader_app_id}"
Done.

2024-05-27 19:49 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +    leader_app_name = f"{APPLICATION_APP_NAME}/{leader_app_id}"
Done.

2024-05-28 11:48 UTC, marceloneppel approved these changes
LGTM!

2024-05-28 12:29 UTC, merged