[DPE-4530] CI testing both forward (Juju) and backwards (focal)
canonical/data-platform-libs pull request #172
Opened 2024-05-31 15:39 UTC by juditnovak

2024-06-03 16:46 UTC, juditnovak commented on .github/workflows/ci.yaml
> +          # - integration-upgrade-7
A few of these tests are failing _exactly_ because we did not have these tests :sweat_smile: 
(Also, I'm using a few newer features in the tests incompatible with older versions.)

I thought to have a smart skipping mechanism (fixture)... but at the end, due to enhanced complexity combined with the fact that --thanks to these tests ;-)-- we shouldn't need a disabling mechanism in the future... 
I rather decided to switch on bigger version window checks a few versions later.

2024-06-03 17:02 UTC, juditnovak commented on tests/integration/conftest.py
> -        ops_test.build_charm = build_charm
We have never used the CI cache.

The reason is simple. Our test charms are there to test the latest version of our libs.
However, our test charms don't have a copy of the lib. We don't want to copy over multiple times 2500 lines to test charms on every single PR...

Instead we are dynamically copying the latest lib version over to the test charms using a fixture.
But THIS then has to be built dynamically.
THIS is not possible with workflows filling the cache.

For this reason we stick to distrubute the latest version of the lib to test charms on-the-fly, and build them after. Given that our charms are little with limited dependencies, the overheat is not enormous.

2024-06-03 17:05 UTC, juditnovak commented on tox.ini
> +[testenv:integration-db]
Shorter action names thus pipelines naming would get less "chatic" in github displays

2024-06-04 13:23 UTC, welpaolo reviewed
Great improvement in the testing pipeline!

I left some comments in the different files.

2024-06-04 13:23 UTC, welpaolo commented on CONTRIBUTING.md
> +For test charms that may support multiple OS versions (typically for libraries that are expected to work across
```suggestion
For test charms that may support multiple Ubuntu versions (typically for libraries that are expected to work across
```

2024-06-04 13:23 UTC, welpaolo commented on CONTRIBUTING.md
> +By default, with no parameters the first OS version is taken, that's specified in the helper charm's `charmcraft.yaml`.
```suggestion
By default, with no parameters the first Ubuntu version is taken, that's specified in the helper charm's `charmcraft.yaml`.
```

2024-06-04 13:23 UTC, welpaolo commented on CONTRIBUTING.md
> +In case any further OS versions are to be used when executing the tests, the following `pytest` parameters are to be added
```suggestion
In case any further Ubuntu versions are to be used when executing the tests, the following `pytest` parameters are to be added
```

2024-06-04 13:23 UTC, welpaolo commented on .github/workflows/ci.yaml
> +          # - integration-upgrade-7
I would like to have the possibility to specify explicitly the LIBPATCH version that we want to test.
I have the feeling that  many times it will not be meaningful to test just the n-th previous versions.

2024-06-04 13:23 UTC, welpaolo commented on tests/integration/test_rolling_upgrade_from_specific_version.py
>              f"{unit.name}:/var/lib/juju/agents/unit-{unit_name_with_dash}"
I would like to have two checks after the copy commands:
- assertion that the copy command is executed correctly, and
- Validation that the copied library has the desired LIBPATCH version

2024-06-05 06:45 UTC, juditnovak commented on .github/workflows/ci.yaml
> +          # - integration-upgrade-7
We MUST provide compatiblity with all previous versions regarding upgrades. So "looking back" no a number of versions is on one hand essential -- on the other hand it's simple to automate on the pipeline.
As, on the pipeline we don't want to update manually on each release, which previous releases to check against...

It is possible to add this feature, however it would be more heavyweight than what we want to add on our pipelines.
Going back to 'any' version means:
 - the github fetch releases mechanism should go back to ALL commits on `main` (and seek for LIBPATCH increase)
 - we need to add a new pytest option to process the input
 
 Also, modifications on these tests were outside of the scope of this PR. If possible, I'd rather not block this PR on those.
 
 I think we gain more by increasing test coverage before my holidays (keeping the team safer than we are with current pipelines) than polishing these tests for better local execution usability, no?
 
 Having said all that, I'd be very happy to add the feature you are requesting when I'm back from holidays :-)

2024-06-05 06:47 UTC, juditnovak commented on tests/conftest.py
> +        "--dp-libs-series", help="Ubuntu series for dp libs charm (e.g. jammy)", default="jammy"
Or... would you be OK with `ubuntu_series`? Or `os_series`? 

I agree that the current naming isn't great :-)

2024-06-05 06:52 UTC, juditnovak commented on tox.ini
> +[testenv:integration-upgrade-{1,2,3,4,5,6,7}]
See my response [above](https://github.com/canonical/data-platform-libs/pull/172#discussion_r1627075399).

v17 (last databag version) we are actually testing against in a separate pipeline, specifically :-)

I agree with you that it would be a good feature. However to me that is on top of what we have here.
As for the pipelines, we should rather have a simple, automated system in the first place, checking a good level of backwards compatibility. We should have this mechansim safe in a way that we don't rely on the developer manually adding `latest-1` version to any `tox.ini` or `ci.yaml`-s whenever `latest` is increaising version -- otherwise missed from backwards compatiblity testing.
Which is the reason why I went for the "backwards time window in the first place in https://github.com/canonical/data-platform-libs/pull/170 , where this test was implemented.

As much for manual runs, as for specifically testing against dedicated older versions (like v17 typically) is a very good idea, however I would take the implementation out of the scope of this PR.

2024-06-05 06:55 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
>              f"{unit.name}:/var/lib/juju/agents/unit-{unit_name_with_dash}"
Is it possible to take requests regarding `test_rolling_upgrade_from_specific_version.py` outside of the scope of this PR, please?

Note that this PR is not addressing those tests in the first place. I'm glad to address related requests in a separate ticket.

2024-06-05 07:02 UTC, juditnovak commented on .github/workflows/ci.yaml
> +          # - integration-upgrade-7
In response of 'meaningful' tests :-)

The lib _must_ be ready to roll over from a previous version to a new one. I mean, these tests should be meaninful each time. Even if 'theoretically' minor, non-essential changes were added, compatibility checks must be preserverd.

2024-06-05 07:09 UTC, juditnovak commented on .github/workflows/ci.yaml
> +          # - integration-upgrade-7
Ah, and +1 consideration.

I had non-negligable amount of discussions with @carlcsaposs-canonical regarding how and when the current "non-conform" pipelines would be migrated to re-usable workflows. 

Currently we are using "non-standard options" that are:
 - either similarly used in other DP charms (`mysql-router-operator`)
 - or should have workarounds to make them more 'conform'
 
 I would like to be careful with any divergence from reusable workflows policies, not to make our lives much harder when we move on to those. Specifying test parameters in new pytest options may be getting tricky to migrate.
Note that the current solution is purposefully not doing that.

2024-06-05 07:58 UTC, welpaolo commented on tests/integration/test_rolling_upgrade_from_specific_version.py
>              f"{unit.name}:/var/lib/juju/agents/unit-{unit_name_with_dash}"
I feel that those checks are really important. I believe you can implement them with two lines of codes.
```python
assert x ==0
```
and the second check could be done with a `grep` command

2024-06-05 08:04 UTC, welpaolo commented on tox.ini
> +[testenv:integration-upgrade-{1,2,3,4,5,6,7}]
I noticed this while reviewing the code but I also notice that there is quite a bit of overlapping code between the two tests. In an ideal world we may have the same tests on both `test_rolling_upgrade_from_specific_version.py` and `tests/integration/test_rolling_upgrade.py` with a correct parametrization of the version to test

2024-06-05 08:05 UTC, welpaolo commented on tests/conftest.py
> +        "--dp-libs-series", help="Ubuntu series for dp libs charm (e.g. jammy)", default="jammy"
both the options are fine with me! @marceloneppel what do you think?

2024-06-05 08:07 UTC, welpaolo commented on .github/workflows/ci.yaml
> +          # - integration-upgrade-7
I believe that we must use re-usable workflow when possible. However, if this is overcomplicating our life or does not fit the test cases we can still use the current approach and keep maintaining it

2024-06-06 11:47 UTC, juditnovak commented on .github/workflows/ci.yaml
> +          # - integration-upgrade-7
Yes, that is exactly what is happening right now. Not because if would overcomplicate things, but rather because it can't respond to our needs (regarding multiple OS solution).

And of course, reusable worklfows are to facilitate our life and not the other way around :-D

On the other hand, it's also important to keep in mind, that in a long term we're better of using worklowst that --after all-- respond to the majority of our charm's needs. What I mean is that, it's good to keep in mind the direction where we want to go, and choose the best tradeoff not to diverge too far from that. Both for leaving the option of migration open, and to make it preferably smooth.

2024-06-06 14:07 UTC, welpaolo approved these changes

2024-06-06 18:37 UTC, marceloneppel commented on tests/conftest.py
> +        "--dp-libs-series", help="Ubuntu series for dp libs charm (e.g. jammy)", default="jammy"
I'd prefer `base` (equals to `ubuntu@20.04` and `ubuntu@22.04`) to be in sync with `juju deploy` in  Juju `3.something` (where the `series` parameter is deprecated) if it's supported in all the versions that are being tested (especially 2.9).

2024-06-06 21:07 UTC, marceloneppel requested changes

2024-06-07 07:20 UTC, juditnovak commented on .github/workflows/ci.yaml
> +      # - build
Done.

2024-06-07 07:29 UTC, juditnovak commented on tests/conftest.py
> +        "--dp-libs-series", help="Ubuntu series for dp libs charm (e.g. jammy)", default="jammy"
Would it be possible to do that in a different PR after my holidays, please?

I would _really_ like to get this change merged ls that libs modifiatinon are safer in my absence. (The current pipelines addtions would have saved us from breaking compatibilyt earlier -- I'd like to securize that this couldn't happen).

As long as `charmcraft` and `OpsTest.buld_charm` understand the terminology you propose, we could go with it.
In which case I'm glad to implement it when I'm back.

Othwrise: we shouldn't put addtitional translation logic, etc.. into something that is probably a temporary feature.
All this `series` and `bases_index`, and so on is likely to change, once we can move to reusable workflows that provide support for testing for multiple OS versions on the pipeliens.

2024-06-07 07:31 UTC, juditnovak commented on tests/conftest.py
> +        "--dp-libs-series", help="Ubuntu series for dp libs charm (e.g. jammy)", default="jammy"
As @welpaolo requested I changed the parameters to `os_series` and `build_bases_index`.

I think it is "good enough" for a temporary solution -- and we should focus on the beenfit of having safe coverage for the whole team, ensuring no breaking changes may happen when reviewers capacity is limited on the libs.

2024-06-07 07:35 UTC, juditnovak commented on tox.ini
> +[testenv:integration-upgrade-{1,2,3,4,5,6,7}]
They are similar indeed, as one served a base for the other ;-)

Yet I still prefer to have a dedicated pipeline just for the `databag` -> `secrets` move, where I'm checking specificities of the databag, secrets, where did a field get defined, etc.

The new modules are generic, only checking for interface-level functionality. They shouldn't have the additional logic that is in the "databag test module". Generally, they shouldn't have custom logic really. They should ensure smooth usage of the libs, as done in the charms -- and as it is not to change withing the same major version of a lib.

Of course the generic module is still to be extended with further tests, but at least for now base worklfows are well covered.

(TBH regarding test module changes I'd rather like to add "extras" such as testing against real charms we've got... It's been a plan that I've got for a while... :-) )

2024-06-07 07:35 UTC, juditnovak commented on CONTRIBUTING.md
> +For test charms that may support multiple OS versions (typically for libraries that are expected to work across
Done.

2024-06-07 07:35 UTC, juditnovak commented on CONTRIBUTING.md
> +By default, with no parameters the first OS version is taken, that's specified in the helper charm's `charmcraft.yaml`.
Done

2024-06-07 07:35 UTC, juditnovak commented on CONTRIBUTING.md
> +In case any further OS versions are to be used when executing the tests, the following `pytest` parameters are to be added
Done

2024-06-07 07:36 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +        ret_code, stdout, y = await ops_test.juju(*complete_command.split())
Done

2024-06-07 07:38 UTC, juditnovak commented on .github/workflows/ci.yaml
> +            libjuju-version: "3.5.0.0"
In the **Description** of the PR I've added all the Juju vesions that --to my knowledge-- we should be supporring.

We surely provide backwards compatiblity to Juju 2.9, and as far as I know the team is already using charms on Juju 3.4. I feel reasponsible make sure that the lib is compatible with the usege the team is applying it for.

2024-06-07 07:38 UTC, juditnovak commented on .github/workflows/ci.yaml
> +            juju-version: {juju-snap-channel: "2.9/stable"}
This is the `excludes` list :-)

So yes, we _do_ focus on Juju 3: that's why we exclude all these secrets-related pipelines on Juju2 :-)

2024-06-07 07:39 UTC, juditnovak commented on .github/workflows/ci.yaml
> +            juju-version: {juju-snap-channel: "2.9/stable"}
NOTE: The last one (`databag`) is manually simulating the `databag` -> `secrets` upgrade. It should be run on Juju3 (as on Juju2 we can't upgrade to secrets, so the pipelne can't be executed).

2024-06-07 07:46 UTC, welpaolo approved these changes

2024-06-07 09:35 UTC, juditnovak commented on CONTRIBUTING.md
> + - `do_libs_base_index`: The number of item in order (counting from `0`) referring to the `db_libs_series` specified in the
Fixed (with the latest-and-graetest terminology :-) )

2024-06-07 09:54 UTC, juditnovak commented on tests/integration/test_rolling_upgrade_from_specific_version.py
> +        ret_code, stdout, y = await ops_test.juju(*complete_command.split())
Done

2024-06-07 09:57 UTC, juditnovak commented on .github/workflows/ci.yaml
> +            libjuju-version: "3.5.0.0"
...in other words: if we can ensure stabilty on our level for the team, that overall helps us to have more stable products. That on its own ("mandatory" or not) is a good enough argument that I would really like to do whatever could be done on my side :-)

Also, given how lightweight our pipelines are, I'm not introducing a massive overhead in this PR.

2024-06-07 09:59 UTC, juditnovak commented on .github/workflows/ci.yaml
> +            libjuju-version: "3.5.0.0"
...also, regarding backwards compatibility the corresponding MM discussion is referred in the **Description**. You may have been thiking of that one.

2024-06-12 21:23 UTC, marceloneppel commented on .github/workflows/ci.yaml
> +            libjuju-version: "3.5.0.0"
> In the **Description** of the PR I've added all the Juju vesions that --to my knowledge-- we should be supporring.
> 
> We surely provide backwards compatiblity to Juju 2.9, and as far as I know the team is already using charms on Juju 3.4. I feel reasponsible make sure that the lib is compatible with the usege the team is applying it for.

My question concerns that list specifically. Do we have charms that support, for example, Juju 3.2 and 3.3? If not, IMO those versions should be removed from the tests.

2024-06-12 21:31 UTC, marceloneppel commented on .github/workflows/ci.yaml
> +            juju-version: {juju-snap-channel: "2.9/stable"}
Got it. Thanks!

2024-06-26 13:31 UTC, juditnovak commented on .github/workflows/ci.yaml
> +            libjuju-version: "3.5.0.0"
None of _our_ charms ;-)

We're offering these libs to a wide number of "external" charms (wordpress, discourse, etc.)
I think it's helpful to make sure that our libs are compatible with Juju versions not strictly within the DP charms scope.

2024-06-26 13:42 UTC, marceloneppel approved these changes

2024-06-26 13:58 UTC, merged