[DPE-4772] Subordinate scale up
canonical/data-platform-libs pull request #180
Opened 2024-07-03 21:30 UTC by dragomirp

2024-07-04 10:46 UTC, dragomirp commented on lib/charms/data_platform_libs/v0/data_interfaces.py
>          diff = self._diff(event)
We should do the subordinate checks before the diff is updated, otherwise custom event behaviour will change.

2024-07-04 10:48 UTC, dragomirp commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +            len(remote_units) == 1
Subordinate relations will have a single remote unit, the one subordinated in the local unit. If we have multiple remote units, we don't have a subordinate relation.

2024-07-04 10:49 UTC, dragomirp commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +            and event.relation.data[remote_units[0]].get("state", "ready") != "ready"
Defaults to ready, so that existing behaviour doesn't change. The subordinate provider should set a different `state` in the `relation_created` hook.

2024-07-05 10:03 UTC, dragomirp commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +
Helper to set the application level flag. If set the Requirer will do the additional subordination checks.

2024-07-05 10:04 UTC, dragomirp commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +                remote_unit_data = event.relation.data[key]
Should only have one remote unit in case of subordinated relation

2024-07-05 12:51 UTC, marceloneppel requested changes

2024-07-05 12:51 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +            if isinstance(key, Unit) and key.name.startswith(self.charm.app.name):
Fix to get the remote unit data:
```suggestion
            if isinstance(key, Unit) and not key.name.startswith(self.charm.app.name):
```

2024-07-05 12:55 UTC, marceloneppel approved these changes
Looks great! Thanks @dragomirp!

2024-07-05 15:36 UTC, delgod approved these changes

2024-07-05 17:21 UTC, paulomach approved these changes
Goog. Left a question

2024-07-05 17:21 UTC, paulomach commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +            if remote_unit_data.get("state") != "ready":
who/where does `ready` is set?

2024-07-05 17:35 UTC, dragomirp commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +            if remote_unit_data.get("state") != "ready":
The subordinate provider sets it when the unit is ready.

2024-07-08 10:48 UTC, merged

2024-07-08 11:09 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +                remote_unit_data = event.relation.data[key]
As commented on the related PR: https://github.com/canonical/pgbouncer-operator/pull/274#discussion_r1667025361

This is kind of a "hack" over the concept pf the lib, where cross-charm relations were strictly using `app` data only. That concept must be extended now, instead of direct access to unit/app data in various "random" places within the code. 

I've opened issue https://github.com/canonical/data-platform-libs/issues/182 and I try to address it in the near future (right after mid-cycle)