[MISC] is_resource_created method
canonical/data-platform-libs pull request #40
Opened 2023-01-30 16:20 UTC by deusebio

PR to supersed #27

2023-01-30 16:24 UTC, delgod approved these changes

2023-01-30 16:57 UTC, beliaev-maksim commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +                return True
how will it work for clusters?

can we check per cluster?

2023-01-30 20:21 UTC, welpaolo requested changes

2023-01-30 20:21 UTC, welpaolo commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def is_resource_created(self) -> bool:
I propose to change this function to take as input the `relation_id` since multiple relations can be established. 
```python
def is_resource_created(self, relation_id:int) -> bool:
    assert relation_id in relation.data[relation.app]
    return "username" in relation.data[relation.app][relation_id] and "password" in relation.data[relation.app][relation_id]
```

2023-01-30 22:22 UTC, deusebio commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def is_resource_created(self) -> bool:
uhm, interesting. What about using this business logic: if relation_id is not specified then resource in ALL relations must exists to return true. If the relation_id is provided, we only check for the given relation. I believe this provides a cleaner ux across cases

```
def _is_resource_created_for_relation(relation: Relation):
    return "username" in relation.data[relation.app][relation_id] and \
           "password" in relation.data[relation.app][relation_id]

def is_resource_created(self, relation_id: Optional[int]) -> bool:
    if relation_id:
        return _is_resource_created_for_relation(self.relations[relation_id])
    else:
        return all([_is_resource_created_for_relation(relation) for relation in self.relations])
```

2023-01-30 22:23 UTC, beliaev-maksim commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def is_resource_created(self) -> bool:
> if relation_id is not specified then resource in ALL relations must exists to return true. If the relation_id is provided, we only check for the given relation. 

I like it

2023-01-31 22:09 UTC, natalian98 approved these changes

2023-02-01 08:47 UTC, beliaev-maksim requested changes

2023-02-01 08:47 UTC, beliaev-maksim commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +                otherwise the checks is done for all relations
```suggestion
        Args:
            relation_id (int, optional): When provided the check is done only for the relation id provided,
                otherwise the check is done for all relations
```

2023-02-01 08:54 UTC, beliaev-maksim approved these changes

2023-02-01 09:15 UTC, welpaolo approved these changes

2023-02-01 17:41 UTC, merged