[ISSUE-45] Update documentation and data_interface library dependency
canonical/data-platform-libs pull request #46
Opened 2023-02-17 15:46 UTC by deusebio

Addressing #45

2023-02-17 16:06 UTC, welpaolo approved these changes
Looks good to me!

2023-02-17 16:07 UTC, marceloneppel approved these changes
LGTM!

2023-02-17 16:14 UTC, NucciTheBoss requested changes

2023-02-17 16:14 UTC, NucciTheBoss commented on README.md
> +The libraries are compatible with `ops>=2.0`.
It might be better to have this as the following:

```suggestion
> __Note:__ `data_interfaces` is not compatible `ops<=1.5.4`. It is compatible with only `ops>=2.0.0`. 
```

This way it is very clear to the reader that `data_interfaces` will not work if being used with an older version of ops, and if you want to use the library, then you need to be on at least ops==2.0.0. With how it is now, it is not clear that `data_interfaces` is not backwards compatible with older versions of ops.

2023-02-18 15:31 UTC, NucciTheBoss approved these changes
LGTM! Thank you for putting in the work  @deusebio :smile:

2023-02-18 15:34 UTC, merged