[DPE-2269] Added k8s upgrade handler
canonical/data-platform-libs pull request #77
Opened 2023-07-17 15:10 UTC by marceloneppel

2023-07-17 22:15 UTC, marcoppenheimer requested changes

2023-07-17 22:15 UTC, marcoppenheimer commented on lib/charms/data_platform_libs/v0/upgrade.py
> +            Iterable of integer unit.ids, LIFO ordered in upgrade order
**praise:** Thank you!

2023-07-17 22:15 UTC, marcoppenheimer commented on lib/charms/data_platform_libs/v0/upgrade.py
> +
**todo:** I think we should remove this block.

It's a good idea to have the function do it (so charm authors / users don't have to remember to do it), but I think we should just be explicit with the documentation that - when handling `upgrade-granted` or `upgrade-finished` - if the unit completes, call `on_upgrade_changed`.

I'm not sure we're using it now, but I wonder if in the future we'd benefit from having an actual `event` to pass, rather than `EventBase(self.handle)`. Not sure.

2023-07-17 22:15 UTC, marcoppenheimer commented on lib/charms/data_platform_libs/v0/upgrade.py
> +        raise NotImplementedError
**question:** Non-blocking, curious, what should charms do when handling this event? You mentioned in the PR description changin gthe `partition` field, do you have an example of that that you could share?

2023-07-18 00:02 UTC, paulomach commented on lib/charms/data_platform_libs/v0/upgrade.py
> +        raise NotImplementedError
One would be [this](https://github.com/canonical/mysql-k8s-operator/blob/0f01b2f4d49a0196c4679014d1de123127c60c1e/src/upgrade.py#L200) , which just control triggering update for a follow up unit

2023-07-18 11:55 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/upgrade.py
> +        raise NotImplementedError
I think so. Let me move it to that hook, so we can probably remove the upgrade-finished hook.

2023-07-18 11:57 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/upgrade.py
> +
I think the library should help the charm authors in ways like this, to not forget to call needed parts of the workflow.

As per the other discussion in this PR, probably we can remove this block as we wouldn't have to trigger upgrade finished. I'm gonna test that.

2023-07-18 13:29 UTC, marceloneppel commented on charmcraft.yaml
> +      - PyYAML # https://github.com/yaml/pyyaml/issues/601
Thanks for the update. Removed the workaround on https://github.com/canonical/data-platform-libs/commit/afc861bda4b622392e8cf85144b83c4765f85837.

2023-07-18 19:11 UTC, paulomach commented on lib/charms/data_platform_libs/v0/upgrade.py
> +                    f"{top_unit} has completed the upgrade, emitting `upgrade_finished` event..."
```suggestion
                    f"{top_unit.name} has completed the upgrade, emitting `upgrade_finished` event..."
```

2023-07-19 13:16 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/upgrade.py
> +                    f"{top_unit} has completed the upgrade, emitting `upgrade_finished` event..."
Good catch! Fixed on https://github.com/canonical/data-platform-libs/pull/77/commits/bf8b2bf0b047d70800a256f214e6aef36e1a827f.

2023-07-19 15:07 UTC, marcoppenheimer approved these changes
Really sensible changes! Left some notes and ideas for future PRs, but nothing blocking.

2023-07-19 15:07 UTC, marcoppenheimer commented on lib/charms/data_platform_libs/v0/upgrade.py
> +        raise NotImplementedError
**thought:** I'm not sure it should block this PR, but leaving idea here.

I wonder if we should implement a k8s-only `abstractmethod` for something like `decrement_partition()`.

That way, we could still call it by default here - hopefully reducing the LoC charm authors need to implement - but we still have the flexibility of doing any other operations around that in the future. It also lines up with the decision you mentioned in an earlier comment about not adding dependencies, as the implementation can be up to the authors.

2023-07-20 20:33 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/upgrade.py
> +        raise NotImplementedError
That's a great idea. I updated the PR in the last commits (https://github.com/canonical/data-platform-libs/pull/77/files/b231d5b827d32c86c8b9d4c2dae801b58ef68894..770245cdff09ac8053c90983a35ac4cce2c0cb70) to address that. I also added the `resume-upgrade` action (only for k8s) because it was mentioned in the `_on_upgrade_finished` method in the and would be another common code for the k8s charms.

I also added the unit test for those new methods (and fixed the existing ones to match the implementation from this PR).

2023-07-25 19:43 UTC, paulomach approved these changes
great

2023-07-25 19:47 UTC, merged