Dpe 2342 relation secrets experimenting secret changed
canonical/data-platform-libs pull request #94
Opened 2023-09-07 06:24 UTC by juditnovak

2023-09-13 16:26 UTC, juditnovak commented on tests/integration/helpers.py
> +        # endpoints = secret_data["endpoints"]
My bad, sry, remainders of experimenting :sweat_smile:

2023-09-13 16:27 UTC, juditnovak commented on tests/integration/test_charm.py
> +            application_charm, application_name=APPLICATION_APP_NAME, num_units=1, series="jammy"
Ah, sry, local testing got committed :sweat_smile: 
Thx very much for noticing!!!!

2023-09-13 16:33 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        """Wrapper function to provide direct access to contained Secret's equal function."""
I'll rephrase. "equally named" is more accurate.

Basicaly the point is to encapsulate all the direct Juju calls (together with an extent of the internal caching).
So that noone would need to directly access Juju Secrets, but all goes through our lilttle local interface over the encapsulated real Juju Secret (inside `CachedSecret`).

I'm adding this "equally called" functoin to support this interface.

2023-09-13 16:39 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        return self._secrets[label]
Good point, I should have done that. Thank U. I add an error on this.

2023-09-14 01:46 UTC, marceloneppel commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        """Wrapper function to provide direct access to contained Secret's equal function."""
Gotcha! Thanks!

2023-09-14 01:47 UTC, marceloneppel approved these changes
Thanks for the updates in the code, @juditnovak!

2023-09-14 11:43 UTC, delgod approved these changes

2023-09-14 11:43 UTC, delgod commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    ) -> Dict[str, str]:
maybe
```suggestion
    @staticmethod
    def _create_secret_content_for_mapping(
        content: Dict[str, str], secret_fields: Set[str], mapping: str
    ) -> Dict[str, str]:
```

2023-09-15 00:30 UTC, benhoyt commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class SecretCache:
Note that we recommend against caching/storing secrets (even in memory). It's best to use `get_secret` / `get_content` each time you need it, to reduce the chance the secret content accidentally gets stored or sent somewhere it shouldn't.

2023-09-17 15:27 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        logger.info("authentication updated at: %s", datetime.now())
:facepalm:

2023-09-17 15:33 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        getattr(self.on, "authentication_updated").emit(relation, app=relation.app)
So here, I'm confused...

Do we have any unit level secrets that may worth processing...? I assume that unit level secrets are to be ignored.... (Only important for the unit itself.)

Other than that, if it's only `app` secrets that we care about: then perhaps unit should always be `None`?

I'm wondering that `self.local_unit` should not be the right thing here, as I guess we --if any `unit`-- then the one that changed the secret should matter, no...?

2023-09-18 09:48 UTC, delgod commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +class SecretCache:
We would love to design it as you say, but because systems with juju < 3.1.5 have performance issues, we decided to use caching.
it is our plan to remove caching in 1y, depending on how fast will juju work with external KMS/Vault in reality.

2023-09-18 12:23 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
>          return data
It's pretty lame that now, even on a single relation query we'll have a 
```
data = {<relation_id>: {key1: value1, ...} }
```
data structure to unpack.

Don't we want to add a new public method like `fetch_specific_relation_data()` or `fetch_per_relation_data()` or so?

2023-09-18 12:23 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
>          return data
(By 'pretty lame' I mean: see how data is retrieved in usages below.)

2023-09-19 17:50 UTC, delgod requested changes

2023-09-19 18:51 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def fetch_relation_field(
My original idea was to provide a "shortcut" when fetching a single field from a single relation.
I think this would be useful to be public.

But I can change it to private if preferred.

2023-09-19 19:04 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        getattr(self.on, "authentication_updated").emit(relation, app=relation.app)
Sure, no intent to change the interface...

However, the currently used unit (`event.unit`) is not `self.local_unit`. 
I double-checked the [docs,](https://ops.readthedocs.io/en/latest/#ops.RelationEvent.unit) `event.unit` is the remote unit, triggering the event.

However what we are doing currently, is taking advantage of the fact that we're processing a `RelationEvent`...

This doesn't hold anymore when processing a `secret-changed` event that doesn't have this feature (i.e. `unit`).
We don't know what unit has fired the event.

Alltogether: we change the current behavior either way...
Either we provide no unit, or we provide a different unit than the one that triggered the secret change (i.e. change of current interface :-( ).

I'm honestly confused what is the right solution here :-(

2023-09-19 22:42 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +        getattr(self.on, "authentication_updated").emit(relation, app=relation.app)
All right, I came up with a workaround to discover the (a(?)) remote unit -- the one that should be (close to be (?)) responsible for the secret change. How about this?

2023-09-20 00:01 UTC, juditnovak commented on tests/integration/test_charm.py
>              series="jammy",
All right. After an endless number of failures on https://bugs.launchpad.net/juju/+bug/2031631, now I'm actually proposing to decrease the number of units temporarily, until Juju 3.6.1 releases the fix.

I assume that this shouldn't be a major risk, given that we are testing this code against Postgres and Opensearch (assuming additional developments do the same)

2023-09-20 00:46 UTC, juditnovak commented
IMPORTANT NOTE:

The current version of the libs is somewhat triggering https://bugs.launchpad.net/juju/+bug/2031631
As a result I can't get green pipelines.
Neither here, nor for Postgres. 

Here a successful workaround is to decrease the number of units for the `integration-database` to `1`.

For Postgres I have no workaround.

Fix should be available in 3.6.1. What should we do until...?

2023-09-20 08:19 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +    def fetch_relation_field(
It is just soooo ugly to fetch data like
```
tls_ca = requires.fetch_relation_data([event.relation.id], ["tls-ca"])[event.relation_id]
```

I rather wish I could say this in the charms instead:
```
tls_ca = requires.fetch_relation_field(event.relation.id, "tls-ca")
```

Hmmmm....? :pleading_face:

2023-09-20 12:51 UTC, marceloneppel commented
> IMPORTANT NOTE:
> 
> The current version of the libs is somewhat triggering https://bugs.launchpad.net/juju/+bug/2031631 As a result I can't get green pipelines. Neither here, nor for Postgres.
> 
> Here a successful workaround is to decrease the number of units for the `integration-database` to `1`.
> 
> For Postgres I have no workaround.
> 
> Fix should be available in 3.6.1. What should we do until...?

Can you open a ticket so we don't forget to increase the number units back to 2 after the fix is available?

2023-09-20 12:52 UTC, marceloneppel approved these changes
LGTM! Thanks Judit!

2023-09-20 14:04 UTC, merged

2023-09-20 16:14 UTC, juditnovak commented
@marceloneppel FYI: Sure, I was planning to open a Jira ticket for myself.
Now, in the meanwhile I got a green pipeline (after MANY attempts)... So for now it's the original state left.
We may still wanna think of the change -- or, alterntatively to use `edge` until the fix is not in `stable` (it's confirmed to be in `edge` already)